const IconName = {
  ARROW_DOWN_LONG: 'arrow down long',
  CARET_DOWN: 'caret down',
  CHEVRON_DOWN: 'chevron down',
  CHEVRON_LEFT: 'chevron left',
  CHEVRON_UP: 'chevron up',
  EYE: 'eye',
  EDIT: 'edit',
  GEAR: 'gear',
  LOCATION_DOT: 'location dot',
  MAP: 'map',
  PLUS: 'plus',
  STAR: 'star',
  TRASH: 'trash',
  CLOUD_UPLOAD: 'cloud-upload',
  FILE: 'file',
  CHECK: 'check',
  LIST: 'list',
  BARS: 'bars',
  XMARK: 'xmark',
  CLOCK_ROTATE_LEFT: 'clock rotate left',
  USER_PEN: 'user pen',
  RIGHT_FROM_BRACKET: 'right from bracket',
  TRUCK: 'truck',
  USERS: 'users',
} as const;

export { IconName };
