export { TruckTowType } from './tow-truck-type.enum.js';
export { TruckCapacity } from './truck-capacity.enum.js';
export { TruckCarsQuantity } from './truck-cars-quantity.enum.js';
export { TruckLicensePlateNumber } from './truck-license-plate-number.enum.js';
export { TruckManufacturer } from './truck-manufacturer.enum.js';
export { TruckPricePerKm } from './truck-price-per-km.enum.js';
export { TruckValidationMessage } from './truck-validation-message.enum.js';
export { TruckYear } from './truck-year.enum.js';
export { TruckApiPath } from './trucks-api.path.enum.js';
