const TRUCK_IMG_WIDTH = 146;
const TRUCK_IMG_HEIGHT = 168;
const TRUCK_IMG_ANCHOR_X = 73;
const TRUCK_IMG_ANCHOR_Y = 84;
const TRUCK_IMG_SCALE = 1;
const MAP_INFO_WINDOW_WIDTH = 250;
const DEFAULT_ZOOM = 16;
const DEFAULT_CENTER = { lat: 50.45, lng: 30.5241 };

export {
  DEFAULT_CENTER,
  DEFAULT_ZOOM,
  MAP_INFO_WINDOW_WIDTH,
  TRUCK_IMG_ANCHOR_X,
  TRUCK_IMG_ANCHOR_Y,
  TRUCK_IMG_HEIGHT,
  TRUCK_IMG_SCALE,
  TRUCK_IMG_WIDTH,
};
