const TRUCK_IMG_WIDTH = 146;
const TRUCK_IMG_HEIGHT = 168;
const TRUCK_IMG_ANCHOR_X = 73;
const TRUCK_IMG_ANCHOR_Y = 84;

export {
  TRUCK_IMG_ANCHOR_X,
  TRUCK_IMG_ANCHOR_Y,
  TRUCK_IMG_HEIGHT,
  TRUCK_IMG_WIDTH,
};
